apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "proj/jeff/ProjApps"
          objectType: "secretsmanager"
          objectAlias: "ProjAppsAlias"
          jmesPath:
          - path: "CLUSTER_TYPE"
            objectAlias: "CLUSTER_TYPE"
          - path: "REGISTRY_USER"
            objectAlias: "REGISTRY_USER"
          - path: "REGISTRY_PASSWORD"
            objectAlias: "REGISTRY_PASSWORD"
          - path: "KC_ARGOCD_CLIENT_SECRET"
            objectAlias: "KC_ARGOCD_CLIENT_SECRET"
  secretObjects:
  - secretName: from-sm-private-git-server
    type: kubernetes.io/basic-auth
    data:
    - objectName: REGISTRY_USER
      key: username
    - objectName: REGISTRY_PASSWORD
      key: password
  - secretName: from-sm-environment-vars
    type: Opaque
    data:
    - objectName: CLUSTER_TYPE
      key: CLUSTER_TYPE
    - objectName: REGISTRY_USER
      key: REGISTRY_USER
    - objectName: REGISTRY_PASSWORD
      key: REGISTRY_PASSWORD
    - objectName: KC_ARGOCD_CLIENT_SECRET
      key: KC_ARGOCD_CLIENT_SECRET
