---
apiVersion: v1
kind: Secret
metadata:
  name: gotk-secret
type: Opaque
data:
  gotk-junk: dmFsdWUtMg==
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: eks-secrets-store-repo
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/thecodebeneath/eks-secrets-store-csi-driver
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-eks-secrets-store
  namespace: default
spec:
  interval: 5m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: eks-secrets-store-repo
  path: "./ks"
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: gotk-secret